import = [
  "~/.config/alacritty/themes/smoooooth.toml",
]
working_directory = "None"
live_config_reload = true

[shell]
program = "/opt/homebrew/bin/tmux"

[window]
padding = { x = 20, y = 20 }
decorations = "Transparent"
opacity = 0.7
blur = true
dynamic_padding = true
startup_mode = "Maximized"

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 15

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Block", blinking = "Always" }
